name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

#     steps:

#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - uses: actions/checkout@v3
#     - name: Docker buildx
#       run: docker buildx create --use
#     - name: Build the Docker image
#       run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t dravenk/drupal:latest drupal/10/fpm --push
