name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 1 * *' # Monthly
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - uses: actions/checkout@v3
      - name: Docker buildx
        run: docker buildx create --use
     
      - name: Build the Docker image
        uses: actions/checkout@v3
      - run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t dravenk/drupal:latest drupal/10/fpm --push

      - name: Build and push - Drupal 10
        id: docker_build_10
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: ./10/
          push: true
          tags: | 
            dravenk/drupal:10
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dravenk/drupal